#!/usr/bin/perl
use strict;
use warnings;

use Data::Dumper;
use Encode;
use FindBin;
use File::Spec;
use File::Basename;
use File::Path;
use lib File::Spec->catfile($FindBin::Bin, '..', 'lib');

use Archive::Lha::Decode;
use Archive::Lha::Header;
use Archive::Lha::Stream::File;
use Carp;
use Time::Moment;

my $controller = +{
    d => sub {
        my $fname = shift or usage();
        my $stream = open_archive($fname);
        while ( defined( my $level = $stream->search_header ) ) {
            my $header = Archive::Lha::Header->new(
                level  => $level,
                stream => $stream
            );
            $stream->seek( $header->data_top );
            _decode_entry($header, $stream);
            print Dumper($header);
        }

    },
    l => sub {
        my $fname = shift or usage();
        _list_lhasa($fname, 'l');
    },
    lv => sub {
        my $fname = shift or usage();
        _list_lhasa($fname, 'lv');
    },
    v => sub {
        my $contents = '';
        my $fname = shift or usage();
        my $stream = open_archive($fname);
        my $totals = { original_size => 0, encoded_size => 0, count => 0 };
        print "Original  Packed Ratio    Date     Time    Name\n";
        print "-------- ------- ----- --------- --------  -------------\n";
        while ( defined( my $level = $stream->search_header ) ) {
            my $header = Archive::Lha::Header->new(
                level  => $level,
                stream => $stream
            );
            $stream->seek( $header->data_top );
            _decode_entry($header, $stream);

            $totals->{original_size} += $header->{original_size};
            $totals->{encoded_size}  += $header->{encoded_size};
            $totals->{count}         += 1;
            printf "%8d %7d%5.1f%% %s %s  %s\n",
              $header->{original_size},
              $header->{encoded_size},
              (($header->{encoded_size} && $header->{original_size}) ? 100 * ($header->{original_size} - $header->{encoded_size}) / $header->{original_size} : 0),
              Time::Moment->from_epoch($header->{timestamp})->strftime("%d-%b-%y"),
              Time::Moment->from_epoch($header->{timestamp})->strftime("%T"),
              Encode::encode_utf8(Encode::decode('iso-8859-15', $header->pathname));
        }
        print "-------- ------- ----- --------- --------\n";
        printf "%8d %7d%5.1f%% %s %s  %s\n",
             $totals->{original_size},
             $totals->{encoded_size},
             (($totals->{encoded_size} && $totals->{original_size}) ? 100 * ($totals->{original_size} - $totals->{encoded_size}) / $totals->{original_size} : 0),
             Time::Moment->from_epoch((stat($fname))[9])->strftime("%d-%b-%y"),
             Time::Moment->from_epoch((stat($fname))[9])->strftime("%T"),
             (sprintf(" %d files", $totals->{count}));
    },
    vv => sub {
        my $fname = shift or usage();
        my $stream = open_archive($fname);
        my $totals = { original_size => 0, encoded_size => 0, count => 0 };
        print "Original  Packed Ratio    Date     Time     Atts   Method CRC  L OS\n";
        print "-------- ------- ----- --------- -------- -------- ------ ---- -----\n";
        while ( defined( my $level = $stream->search_header ) ) {
            my $header = Archive::Lha::Header->new(
                level  => $level,
                stream => $stream
            );
            $stream->seek( $header->data_top );
            _decode_entry($header, $stream);

            $totals->{original_size} += $header->{original_size};
            $totals->{encoded_size}  += $header->{encoded_size};
            $totals->{count}         += 1;

            my $name = Encode::encode_utf8(Encode::decode('iso-8859-15', $header->pathname));
            my $os_char = uc($header->{os}[0] // '?');
            my $hdr_level = ref($header) =~ /Level(\d)/ ? $1 : '?';

            printf "%s\n", $name;
            printf "%8d %7d%5.1f%% %s %s ----rwed  -%s- %04x %s %s\n",
              $header->{original_size},
              $header->{encoded_size},
              (($header->{encoded_size} && $header->{original_size}) ? 100 * ($header->{original_size} - $header->{encoded_size}) / $header->{original_size} : 0),
              Time::Moment->from_epoch($header->{timestamp})->strftime("%d-%b-%y"),
              Time::Moment->from_epoch($header->{timestamp})->strftime("%T"),
              $header->{method},
              $header->{crc16},
              $hdr_level,
              $os_char;
        }
        print "-------- ------- ----- --------- --------\n";
        printf "%8d %7d%5.1f%% %s %s  %s\n",
             $totals->{original_size},
             $totals->{encoded_size},
             (($totals->{encoded_size} && $totals->{original_size}) ? 100 * ($totals->{original_size} - $totals->{encoded_size}) / $totals->{original_size} : 0),
             Time::Moment->from_epoch((stat($fname))[9])->strftime("%d-%b-%y"),
             Time::Moment->from_epoch((stat($fname))[9])->strftime("%T"),
             (sprintf(" %d files", $totals->{count}));
    },
    t => sub {
        my $fname = shift or usage();
        printf "Testing integrity of archive '%s':\n", $fname;
        my $stream = open_archive($fname);
        my $totals = { original_size => 0, encoded_size => 0, count => 0 };
        while ( defined( my $level = $stream->search_header ) ) {
            my $header = Archive::Lha::Header->new(
                level  => $level,
                stream => $stream
            );
            $stream->seek( $header->data_top );
            _decode_entry($header, $stream);

            $totals->{original_size} += $header->{original_size};
            $totals->{encoded_size}  += $header->{encoded_size};
            $totals->{count}         += 1;
            printf "    Testing: (%8d/%8d)  %s\n", $header->{original_size}, $header->{original_size}, Encode::encode_utf8(Encode::decode('iso-8859-15', $header->pathname));
        }
        my $error = undef;
        if ($totals->{count}) {
            if (!$error) {
              printf "%d files tested, all files OK\n", $totals->{count};
            }
        } else {
            $error = 1;
            printf "No files tested.\n";
        }
        if ($error) {
            printf "\nOperation not entirely successful\n\n";
        } else {
            printf "\nOperation succesful\n\n";
        }
=pod
     WARNING: Skipping corrupt/extraneous data
No files tested.

Operation not entirely successful

---
    Testing: (   12345/   12345)  file-name
    …
129 files tested, all files OK

Operation successful

=cut
    },
    x => sub {
        my $fname = shift or usage();
        my %target;
        if (@_) {
            %target = map { $_ => 1 } @_;
        }
        my $stream = open_archive($fname);
        while ( defined( my $level = $stream->search_header ) ) {
            my $header = Archive::Lha::Header->new(
                level  => $level,
                stream => $stream
            );
            if ( %target and !$target{$header->pathname} ) {
                $stream->seek( $header->next_header );
                next;
            }
            $stream->seek( $header->data_top );

            if (_is_directory($header)) {
                mkpath $header->pathname unless -d $header->pathname;
                next;
            }

            my ($decoded, $crc) = _decode_entry($header, $stream);
            die "crc mismatch" if $crc != $header->crc16;

            write_all($header->pathname, $decoded);
        }
    },
};

&main;exit;

sub main {
    my $cmd = shift @ARGV or usage();
    my $file = shift @ARGV or usage();
    check_magic($file);
    $controller->{$cmd}->($file, @ARGV);
}

sub usage {
    die "Usage: $0 (l|lv|v|vv|x|t|d) archive (files)\n l  - list contents (lhasa l format)\n lv - list contents (lhasa v format)\n v  - list archive verbose (LhA v format)\n vv - list archive full (LhA vv format)\n x  - extract archive\n t  - test file\n d  - dump each header\n";
}

# ls-style date: show time if within ~6 months, year otherwise
sub _ls_stamp {
    my ($epoch) = @_;
    my $now = time;
    my $six_months = 180 * 86400;
    my $tm = Time::Moment->from_epoch($epoch);
    if (abs($now - $epoch) < $six_months) {
        return $tm->strftime("%b %e %H:%M");
    }
    return $tm->strftime("%b %e  %Y");
}

# Lhasa-compatible listing (l = terse, lv = verbose with method+crc)
sub _list_lhasa {
    my ($fname, $mode) = @_;
    my $stream = open_archive($fname);
    my $totals = { original_size => 0, encoded_size => 0, count => 0 };

    if ($mode eq 'lv') {
        printf " PERMSSN    UID  GID    PACKED    SIZE  RATIO METHOD CRC     STAMP          NAME\n";
        printf "---------- ----------- ------- ------- ------ ---------- ------------ -------------\n";
    } else {
        printf " PERMSSN    UID  GID      SIZE  RATIO     STAMP           NAME\n";
        printf "---------- ----------- ------- ------ ------------ --------------------\n";
    }

    while ( defined( my $level = $stream->search_header ) ) {
        my $header = Archive::Lha::Header->new(
            level  => $level,
            stream => $stream
        );
        $stream->seek( $header->data_top );
        _decode_entry($header, $stream);

        $totals->{original_size} += $header->{original_size};
        $totals->{encoded_size}  += $header->{encoded_size};
        $totals->{count}         += 1;

        my $stamp = _ls_stamp($header->{timestamp});
        my $name  = Encode::encode_utf8(Encode::decode('iso-8859-15', $header->pathname));
        $name .= '/' if _is_directory($header) && $name !~ m{/$};
        my $prefix = _lhasa_prefix($header);
        my $ratio_str = _is_directory($header) ? '******'
            : sprintf("%5.1f%%", $header->{original_size}
                ? 100 * $header->{encoded_size} / $header->{original_size} : 0);

        if ($mode eq 'lv') {
            printf "%s%8d %7d %s -%s- %04x %s %s\n",
                $prefix,
                $header->{encoded_size},
                $header->{original_size},
                $ratio_str,
                $header->{method},
                $header->{crc16},
                $stamp,
                $name;
        } else {
            printf "%s%7d %s %s %s\n",
                $prefix,
                $header->{original_size},
                $ratio_str,
                $stamp,
                $name;
        }
    }

    if ($mode eq 'lv') {
        printf "---------- ----------- ------- ------- ------ ---------- ------------ -------------\n";
    } else {
        printf "---------- ----------- ------- ------ ------------ --------------------\n";
    }

    my $ratio = $totals->{original_size}
        ? 100 * $totals->{encoded_size} / $totals->{original_size} : 0;
    my $stamp = _ls_stamp((stat($fname))[9]);

    if ($mode eq 'lv') {
        printf " Total        %2d files %8d %7d %5.1f%%            %s\n",
            $totals->{count},
            $totals->{encoded_size},
            $totals->{original_size},
            $ratio,
            $stamp;
    } else {
        printf " Total        %2d files %7d %5.1f%% %s\n",
            $totals->{count},
            $totals->{original_size},
            $ratio,
            $stamp;
    }
}

sub _is_directory { $_[0]->{method} eq 'lhd' }

# Format permission/owner prefix like lhasa does
sub _lhasa_prefix {
    my ($header) = @_;
    if (defined $header->{unix_perm}) {
        my $perm = $header->{unix_perm};
        my $type = _is_directory($header) ? 'd' : '-';
        my $str = $type;
        for my $shift (6, 3, 0) {
            my $bits = ($perm >> $shift) & 7;
            $str .= ($bits & 4) ? 'r' : '-';
            $str .= ($bits & 2) ? 'w' : '-';
            $str .= ($bits & 1) ? 'x' : '-';
        }
        my $uid = $header->{unix_uid} // 0;
        my $gid = $header->{unix_gid} // 0;
        return sprintf "%-10s %5d/%-5d", $str, $uid, $gid;
    }
    return sprintf "%-23s", '[' . ($header->{os}[1] // 'generic') . ']';
}

sub _decode_entry {
    my ($header, $stream) = @_;
    return ('', 0) if _is_directory($header);
    my $decoded = '';
    my $decoder = Archive::Lha::Decode->new(
        header => $header,
        read   => sub { $stream->read(@_) },
        write  => sub { $decoded .= join '', @_ },
    );
    my $crc = $decoder->decode;
    return ($decoded, $crc);
}

sub open_archive {
    my $fname = shift;
    die "fname missing" unless $fname;
    Archive::Lha::Stream::File->new(file => $fname);
}

sub write_all {
    my ($fname, $data) = @_;
    my $dir = dirname($fname);
    mkpath $dir unless -d $dir;
    open my $fh, '>:raw', $fname or die $!;
    binmode $fh;
    print $fh $data;
    close $fh;
}

sub check_magic {
    my $fname = shift;
    open my $fh, '<:raw', $fname;
    binmode $fh;
    my $magic;
    my $chars = read($fh,$magic,5);
    my ($signature) = unpack("x2a3", $magic);
    die 'Does not look like an LHa file' unless $signature eq "-lh";
}

__END__

=head1 NAME

plha - command line tool to extract .lzh archive

=head1 SYNOPSIS

  # From the command line
  > plha v archive.lzh
  > plha x archive.lzh

  # if you want to extract a specific file from the archive
  > plha x archive.lzh pathname_in_the_archive

=head1 DESCRIPTION

plha is a simple command line tool to extract .lzh archives. It shows file list in an archive, and extracts all the files (or selected files) in the current working directory. No pathname conversion nor content filtering. No parent directory for the extracted files. Use this as a skeleton for your custom command line tool. Patches are welcome.

=head1 AUTHOR

Tokuhiro Matsuno <tokuhiro __at__ mobilefactory.jp>

LICENSE AND COPYRIGHT

Copyright (c) 2007, Tokuhiro Matsuno <tokuhiro __at__ mobilefactory.jp>.

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself. See perlartistic.
